<?php

/**
 * Implementation of hook_menu()
 *
 */
function os2web_taxon_api_menu() {
  $items['os2web/taxon/test'] = array(
    'title' => t('Taxon test page'),
    'description' => t('taxon api test page.'),
    'access arguments' => array('administer os2web'),
    'page callback' => 'os2web_taxon_api_page',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Test page for abitrary test usage
 *
 * @access public
 * @return void
 */
function os2web_taxon_api_page() {
  $tmp = '<textarea cols=100 rows=50>';
  $tmp .= print_r(os2web_taxon_api_get_terms("hegnssyn og naboejendom",2) ,true);
  $tmp .= '</textarea>';
  return $tmp;
}


/**
 * Implementation of hook_init()
 */
function os2web_taxon_api_init() {
}

function os2web_taxon_api_get_terms($text,$number_results_returned) {
  $taxon = _os2web_taxon_api_get_instance();
  $json = $taxon->getNames($text,$number_results_returned);
  $result = array();
  foreach( $json as $term )
  {
	$result += taxonomy_get_term_by_name($term, 'kle');
  }
  return $result;
}


/**
 * Factory for class instances. This allows easy changing between api classes.
 * TODO: Make this proper plugin-able.
 *
 * @return TaxonWS object
 */
function _os2web_taxon_api_get_instance() {
  $obj = &drupal_static(__FUNCTION__);
  if (is_object($obj))
    return $obj;
  module_load_include('inc', 'os2web_taxon_api', 'TaxonWS.class');
  return $obj = new TaxonWS();
}

